#!/usr/bin/env bash
echo -e "---------------------------------------------\n"
echo "CVE FINDER ... "

python3 ThreatTracer/cvefinder.py ${DOMAIN}

echo -e "---------------------------------------------\n"