#!/usr/bin/env bash
echo -e "---------------------------------------------\n"
echo "WAPPLE ... "

python3 /home/kali/ost/ThreatTracer/wapple.py ${DOMAIN}
echo -e "---------------------------------------------\n"